const CONFIG = window.LIGA_CONFIG || {};
const TABS = [
  ['overview','Overview','⌘'],['peserta','Peserta','♙'],['inputHasil','Input Hasil','✓'],['klasemen','Klasemen','♜'],['keaktifan','Keaktifan','⌁'],['powerRating','Power Rating','ϟ'],['playerVsPlayer','Player vs Player','◎'],['informasi','Informasi','ⓘ']
];
const SHEETS = { peserta:'Peserta', inputHasil:'Input Hasil', klasemen:'Klasemen', keaktifan:'Keaktifan', powerRating:'Power Rating', playerVsPlayer:'Player vs Player' };
const fallback = { peserta:[{nama:'Contoh Peserta',klub:'Liga 9 Pool Family',status:'Aktif'}], inputHasil:[], klasemen:[], keaktifan:[], powerRating:[], playerVsPlayer:[] };
let state = { tab:'overview', tables:{...fallback}, layout:{}, stats:{participants:'—',matches:'—',attendance:'—',topRating:'—'}, source:'preview', query:'' };
const $ = (selector) => document.querySelector(selector);
const esc = (value) => String(value ?? '—').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const title = (key) => TABS.find(x => x[0] === key)?.[1] || key;
function renderNav(){ $('#nav').innerHTML = TABS.map(([key,label,icon]) => `<button class="${state.tab===key?'active':''}" data-tab="${key}">${icon} &nbsp; ${label}</button>`).join(''); document.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>selectTab(el.dataset.tab))); }
function selectTab(tab){ state.tab=tab; state.query=''; $('#searchInput').value=''; $('#sidebar').classList.remove('open'); renderNav(); render(); window.scrollTo({top:0,behavior:'smooth'}); }
function stats(){ return `<div class="stats">${[['PESERTA TERDAFTAR',state.stats.participants,'Pemain di musim ini','♙'],['PERTANDINGAN TERCATAT',state.stats.matches,'Hasil pertandingan','✓'],['KEHADIRAN RATA-RATA',state.stats.attendance,'Komitmen komunitas','⌁'],['POWER RATING TERATAS',state.stats.topRating,'Performa terbaik','ϟ']].map(x=>`<div class="glass stat"><div class="stat-top"><div><div class="stat-label">${x[0]}</div><div class="stat-value">${esc(x[1])}</div></div><span class="stat-icon">${x[3]}</span></div><div class="stat-detail">${x[2]}</div></div>`).join('')}</div>`; }
function overview(){ const leaders=(state.tables.klasemen?.rows||state.tables.klasemen||[]).slice(0,3); return `${stats()}<div class="hero-grid"><div class="hero"><span class="pill">✣ MUSIM II · 2026</span><h2>Satu meja.<br><span class="gold">Satu semangat.</span></h2><p>Pusat informasi resmi Liga 9 Pool Family. Pantau persaingan, performa, dan perjalanan setiap pemain dalam satu ruang.</p><div class="meta">▣ &nbsp; Musim berjalan &nbsp;&nbsp; • &nbsp;&nbsp; ◈ &nbsp; Data terpusat</div></div><div class="glass leaderboard"><div class="eyebrow">PAPAN ATAS</div><div class="section-title">Klasemen sementara</div>${leaders.length?leaders.map((r,i)=>`<div class="leader-row"><span class="rank ${i===0?'first':''}">${i===0?'♛':i+1}</span><span>${esc(r.nama||r.name||Object.values(r)[0])}</span></div>`).join(''):'<div class="leader-empty">Klasemen akan muncul setelah data tersambung.</div>'}</div></div><div class="quick-links"><button class="quick" data-tab="peserta">♙<b>Kenali para peserta</b><span>Profil dan daftar pemain musim ini.</span></button><button class="quick" data-tab="powerRating">ϟ<b>Ukur kekuatan</b><span>Bandingkan performa lewat power rating.</span></button><button class="quick" data-tab="informasi">ⓘ<b>Info dari panitia</b><span>Pengumuman dan agenda terbaru.</span></button></div>`; }
function table(){ const payload=state.tables[state.tab]||{headers:[],rows:[]}; const rows=(payload.rows||[]).filter(r=>!state.query||Object.values(r).some(v=>String(v??'').toLowerCase().includes(state.query.toLowerCase()))); if(!rows.length)return `<div class="empty">Data ${title(state.tab)} siap ditampilkan.<br><br>Belum ada baris terlihat pada Google Sheet.</div>`; const columns=payload.headers||[]; const layout=state.layout?.[state.tab]||{}; const widths=(layout.columns||[]).map(c=>c.width||120); return `<div class="table-wrap"><table style="--sheet-cols:${widths.map(w=>`${w}px`).join(' ')}"><thead><tr>${columns.map((key,i)=>`<th style="width:${widths[i]||120}px">${esc((layout.columns||[])[i]?.label||key)}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr style="height:${r.__height||32}px">${columns.map((key,j)=>`<td style="width:${widths[j]||120}px">${esc(r[key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; }
function information(){ return `<div class="notice-grid"><div><article class="glass notice"><small>MUSIM II · 2026</small><h3>Selamat datang di dashboard Liga 9</h3><p>Gunakan menu navigasi untuk melihat peserta, hasil pertandingan, klasemen, dan analisis performa pemain.</p></article><article class="glass notice"><small>PANITIA · INFORMASI</small><h3>Ruang pengumuman resmi</h3><p>Bagian ini dapat digunakan untuk membagikan jadwal, ketentuan liga, perubahan regulasi, dan apresiasi komunitas.</p></article></div><div class="info-card"><span class="pill">✦ INFORMASI</span><h2>Ruang informasi untuk seluruh pemain.</h2><p>Isi teks informasi berikut dapat diubah langsung di file <code>app.js</code> pada fungsi <code>information()</code>.</p></div></div>`; }
function render(){ const isTable=!['overview','informasi'].includes(state.tab); $('#pageTitle').textContent=title(state.tab); $('#pageSubtitle').textContent=state.tab==='overview'?'Ringkasan performa dan dinamika kompetisi musim ini.':state.tab==='informasi'?'Pusat pengumuman dan informasi dari panitia.':`Data terkurasi dari sheet ${title(state.tab)}.`; $('#tableTools').classList.toggle('hidden',!isTable); $('#content').innerHTML=state.tab==='overview'?overview():state.tab==='informasi'?information():table(); document.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>selectTab(el.dataset.tab))); }
function convertValues(values){ if(!values||values.length<2)return []; const headers=values[0].map((h,i)=>String(h||`Kolom ${i+1}`).trim().replace(/[^a-zA-Z0-9]+(.)/g,(_,c)=>c.toUpperCase())); return values.slice(1).filter(row=>row.some(v=>String(v??'').trim())).map(row=>Object.fromEntries(headers.map((h,i)=>[h,row[i]??null]))); }
async function loadData(){ const id=CONFIG.GOOGLE_SHEET_ID; const bridge=CONFIG.GOOGLE_SHEETS_BRIDGE_URL; if(!id&&!bridge){state.source='preview';state.tables={...fallback};state.stats={participants:'—',matches:'—',attendance:'—',topRating:'—'};return;} try{ let payload; if(bridge){ const res=await fetch(bridge); if(!res.ok)throw new Error(`Google Apps Script ${res.status}`); payload=await res.json(); } else { throw new Error('Google Apps Script bridge belum dikonfigurasi'); } const result={}; const layout={}; Object.entries(SHEETS).forEach(([key,name])=>{ const item=payload.tables?.[name]||{headers:[],rows:[]}; result[key]=item; layout[key]=payload.layout?.[name]||{columns:[],rowHeights:[]}; }); state.tables=result; state.layout=layout; state.source=payload.source||'google-apps-script'; state.stats.participants=result.peserta?.rows?.length||'—'; state.stats.matches=result.inputHasil?.rows?.length||'—'; state.stats.attendance='—'; state.stats.topRating='—'; }catch(error){ console.warn(error);state.source='preview';state.tables={...fallback}; } }
async function refresh(){ $('#refreshBtn').textContent='↻ Memuat...'; await loadData(); render(); $('#refreshBtn').textContent='↻ Refresh'; }
$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;render();$('#searchInput').value=state.query}); $('#refreshBtn').addEventListener('click',refresh); $('#reloadBtn').addEventListener('click',refresh); $('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open')); renderNav(); loadData().then(render);
